NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 0.0
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 40
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 40