NDefines.NAir.COMBAT_MULTIPLANE_CAP = 2;
NDefines.NAir.COMBAT_DAMAGE_SCALE = 0.85;
NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 4;
NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 150;				-- Max stats
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 150;
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 150;
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 800;

NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_DAMAGE_FACTOR = 0.05;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRAIN_DAMAGE_FACTOR = 0.005;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_RAILWAY_DAMAGE_SPILL_FACTOR = 0.001;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_MAX_FACTOR = 0.05;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_DIRECT_DISRUPTION_DAMAGE_FACTOR = 0.002;

NDefines.NAir.BASE_UNIT_WEIGHT_IN_TRANSPORT_PLANES = 35.0;
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0;
