NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2;
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2;
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 3;
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 10000;
NDefines.NMilitary.COHESION_IMMOBILE_PLANNING_SPEED_MULTIPLIER = 1;

NDefines.NMilitary.MAX_NUM_AUTOMEDALS = 1000;
NDefines.NMilitary.NAVAL_INVASION_PLANNING_BONUS_MALUS = -0.8;
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 1.3;
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.58;

NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 40;
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 40;

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999;

NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0;
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0;
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0;