NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_DAMAGE_FACTOR = 0.05;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRAIN_DAMAGE_FACTOR = 0.005;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_RAILWAY_DAMAGE_SPILL_FACTOR = 0.001;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_MAX_FACTOR = 0.05;
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_DIRECT_DISRUPTION_DAMAGE_FACTOR = 0.002;
NDefines.NCountry.FUEL_LEASE_CONVOY_RATIO = 0.0001;
NDefines.NAir.BASE_UNIT_WEIGHT_IN_TRANSPORT_PLANES = 35.0;
NDefines.NCountry.AIR_SUPPLY_CONVERSION_SCALE = 0.05;
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0;
NDefines.NMilitary.NAVAL_INVASION_PLANNING_BONUS_MALUS = -0.8;
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 1.3;
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.58;	

NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 200;
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 200;
NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 250;
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 300;
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 20;


