NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2;

NDefines.NAir.COMBAT_MULTIPLANE_CAP = 2;
NDefines.NAir.COMBAT_DAMAGE_SCALE = 0.85;
NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 4;
NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 150;				-- Max stats
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 150;
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 150;
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 800;

NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2;
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 3;
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 10000;
NDefines.NMilitary.COHESION_IMMOBILE_PLANNING_SPEED_MULTIPLIER = 1;
NDefines.NMilitary.MAX_NUM_AUTOMEDALS = 1000;
